name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1          
      - name: npm install
        env:
          CI: true
        run: npm ci
      - name: Build
        run: npx ncc build index.ts
      - name: Create deployment package
        run: zip -j deploy.zip ./dist/*
      - name: Deploy to Lambda
        run: aws lambda update-function-code --function-name player-ex2-function --zip-file fileb://deploy.zip
