name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        env:
          CI: true
        run : |
          npm ci
      - name: Build
        run: npm run build
      
      - name: Deploy to Lambda
        uses: appleboy/lambda-action@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ca-central-1
          function_name: player-ex2-function
          zip_file: dist/lambda.zip
